# Generated by Django 5.1.2 on 2024-10-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_nickname', models.CharField(max_length=128, unique=True)),
                ('player_name', models.CharField(max_length=150)),
                ('player_email', models.CharField(max_length=250)),
                ('player_phone_number', models.CharField(blank=True, default='', max_length=11)),
                ('player_age', models.IntegerField()),
            ],
        ),
    ]
