# Generated by Django 5.1.2 on 2024-10-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('team_game', models.CharField(max_length=255, unique=True)),
                ('team_quantity_members', models.IntegerField()),
            ],
        ),
    ]
